# EXAMPLE CONFIGURATION.. Change this
devices: 
  - 
    applications: 
      - 
        package_name: "com.orange.be.orangetv"
        should_update: true
    enabled: true
    ip: "192.168.0.12"
    port: 5555
    name: Galaxy S10
timeout: 7200 # Check for updates every 2 hours
provider: apkmirror # apkmirror | aptoide