# EXAMPLE CONFIGURATION.. Change this
devices: 
  - 
    applications: 
      - 
        package_name: "com.orange.be.orangetv"
        should_update: true
    enabled: true
    ip: "192.168.0.12"
    port: 43461
    name: Galaxy S10
    auth_port: 123456 
    auth_code: 6060
  - 
    applications: 
      - 
        package_name: "com.android.chrome"
        should_update: true
        provider: aptoide
      - 
        package_name: "com.google.android.apps.tv.launcherx"
        should_update: false
        provider: apkmirror
    enabled: true
    ip: "192.168.0.6"
    port: 5555
    name: shield
    arch: armeabi-v7a
    api_level: 28
timeout: 7200 # Check for updates every 2 hours
provider: apkmirror # apkmirror | aptoide